In [1]:
import numpy as np
import tensorflow as tf

In [2]:
x = np.array([1.2, 3.6, 9.7])
y = np.array([2.8, 9.4, 1.3])

In [3]:
z = tf.add(x,y)
with tf.Session() as sess:
    init = tf.initialize_all_variables()
    sess.run(init)
    print (z.eval())
print (x + y)

[  4.  13.  11.]
[  4.  13.  11.]


In [4]:
z = tf.sub(x,y)
with tf.Session() as sess:
    init = tf.initialize_all_variables()
    sess.run(init)
    print (z.eval())
print (x - y)

[-1.6 -5.8  8.4]
[-1.6 -5.8  8.4]


In [5]:
z = tf.mul(x,y)
with tf.Session() as sess:
    init = tf.initialize_all_variables()
    sess.run(init)
    print (z.eval())
print (x * y)

[  3.36  33.84  12.61]
[  3.36  33.84  12.61]


In [6]:
"""
Returns x / y element-wise.
"""

z = tf.div(x,y)
with tf.Session() as sess:
    init = tf.initialize_all_variables()
    sess.run(init)
    print (z.eval())
print (x / y)

[ 0.42857143  0.38297872  7.46153846]
[ 0.42857143  0.38297872  7.46153846]


In [7]:
"""
Divides x / y elementwise, always producing floating point results.
"""

z = tf.truediv(x,y)
with tf.Session() as sess:
    init = tf.initialize_all_variables()
    sess.run(init)
    print (z.eval())
print (x / y)

[ 0.42857143  0.38297872  7.46153846]
[ 0.42857143  0.38297872  7.46153846]


In [8]:
"""
Divides x / y elementwise, rounding down for floating point.
"""

z = tf.floordiv(x,y)
with tf.Session() as sess:
    init = tf.initialize_all_variables()
    sess.run(init)
    print (z.eval())
print (x / y)

[ 0.  0.  7.]
[ 0.42857143  0.38297872  7.46153846]


In [9]:
"""
Returns element-wise remainder of division.
"""

z = tf.mod(x,y)
with tf.Session() as sess:
    init = tf.initialize_all_variables()
    sess.run(init)
    print (z.eval())
print (x % y)

[ 1.2  3.6  0.6]
[ 1.2  3.6  0.6]


In [10]:
a = np.array([9, 5, 4])
b = np.array([6, 8, 1])

z = tf.mod(a,b)
with tf.Session() as sess:
    init = tf.initialize_all_variables()
    sess.run(init)
    print (z.eval())
print (a % b)

[3 5 0]
[3 5 0]


In [11]:
z = tf.mod(a,x) # integer % float
with tf.Session() as sess:
    init = tf.initialize_all_variables()
    sess.run(init)
    print (z.eval())
print (a % x)

[0 2 4]
[ 0.6  1.4  4. ]


In [12]:
z = tf.mod(x,b) # float % integer
with tf.Session() as sess:
    init = tf.initialize_all_variables()
    sess.run(init)
    print (z.eval())
print (x % b)

[ 1.2  3.6  0.7]
[ 1.2  3.6  0.7]


In [13]:
z = tf.cross(x,y)
with tf.Session() as sess:
    init = tf.initialize_all_variables()
    sess.run(init)
    print (z.eval())
print (np.cross(x,y))

[-86.5  25.6   1.2]
[-86.5  25.6   1.2]


In [14]:
z = tf.add_n([x,y])
with tf.Session() as sess:
    init = tf.initialize_all_variables()
    sess.run(init)
    print (z.eval())
print (x + y)

[  4.  13.  11.]
[  4.  13.  11.]


In [15]:
c = np.array([1.23, 4.3, 0.3])
z = tf.add_n([x,y, c])
with tf.Session() as sess:
    init = tf.initialize_all_variables()
    sess.run(init)
    print (z.eval())
print (x + y + c)

[  5.23  17.3   11.3 ]
[  5.23  17.3   11.3 ]


In [16]:
c = np.array([-1.23, 4.3, -0.3])
z = tf.abs(c)
with tf.Session() as sess:
    init = tf.initialize_all_variables()
    sess.run(init)
    print (z.eval())
print (np.abs(c))

[ 1.23  4.3   0.3 ]
[ 1.23  4.3   0.3 ]


In [17]:
c = np.array([-1.23, 4.3, -0.3])
z = tf.neg(c)
with tf.Session() as sess:
    init = tf.initialize_all_variables()
    sess.run(init)
    print (z.eval())
print (-c)

[ 1.23 -4.3   0.3 ]
[ 1.23 -4.3   0.3 ]


In [18]:
c = np.array([-1.23, 4.3, -0.3])
z = tf.sign(c)
with tf.Session() as sess:
    init = tf.initialize_all_variables()
    sess.run(init)
    print (z.eval())
print (np.array([-1. if i < 0 else 1. for i in c]))
print (np.sign(c))

[-1.  1. -1.]
[-1.  1. -1.]
[-1.  1. -1.]


In [19]:
c = np.array([-1.23, 4.3, -0.3])
z = tf.inv(c)
with tf.Session() as sess:
    init = tf.initialize_all_variables()
    sess.run(init)
    print (z.eval())
print (1. / c)

[-0.81300813  0.23255814 -3.33333333]
[-0.81300813  0.23255814 -3.33333333]


In [20]:
c = np.array([-1.23, 4.3, -0.3])
z = tf.square(c)
with tf.Session() as sess:
    init = tf.initialize_all_variables()
    sess.run(init)
    print (z.eval())
print (c * c)

[  1.5129  18.49     0.09  ]
[  1.5129  18.49     0.09  ]


In [21]:
c = np.array([-1.23, 4.3, -0.3])
z = tf.round(c)
with tf.Session() as sess:
    init = tf.initialize_all_variables()
    sess.run(init)
    print (z.eval())
print (np.round(c))

[-1.  4.  0.]
[-1.  4. -0.]


In [22]:
c = np.array([-1.23, 4.3, -0.3])
z = tf.sqrt(c)
with tf.Session() as sess:
    init = tf.initialize_all_variables()
    sess.run(init)
    print (z.eval())
print (np.sqrt(c))

[        nan  2.07364414         nan]
[        nan  2.07364414         nan]


In [23]:
c = np.array([-1.23, 4.3, -0.3])
z = tf.rsqrt(c)
with tf.Session() as sess:
    init = tf.initialize_all_variables()
    sess.run(init)
    print (z.eval())
print (-1 / np.sqrt(c))

[        nan  0.48224282         nan]
[        nan -0.48224282         nan]


In [24]:
c = np.array([-1.23, 4.3, -0.3])
z = tf.rsqrt(c)
with tf.Session() as sess:
    init = tf.initialize_all_variables()
    sess.run(init)
    print (z.eval())
print (-1 / np.sqrt(c))

[        nan  0.48224282         nan]
[        nan -0.48224282         nan]
